src/main/java/com/dace/dmgr/DMGR.java, src/main/java/com/dace/dmgr/config/GeneralConfig.java, src/main/java/com/dace/dmgr/event/Chat.java, src/main/java/com/dace/dmgr/event/ResourcePack.java, src/main/java/com/dace/dmgr/event/ServerJoin.java, src/main/java/com/dace/dmgr/event/ServerQuit.java, src/main/java/com/dace/dmgr/system/command/LobbyCommand.java, src/main/java/com/dace/dmgr/system/command/SelectCharCommand.java, src/main/java/com/dace/dmgr/user/Lobby.java, src/main/java/com/dace/dmgr/user/User.java, src/main/java/com/dace/dmgr/user/UserConfig.java
=> Feature/코드 구조 개편

pom.xml, src/main/java/com/dace/dmgr/DMGR.java, src/main/java/com/dace/dmgr/event/InventoryClick.java, src/main/java/com/dace/dmgr/event/PlayerChat.java, src/main/java/com/dace/dmgr/event/PlayerJoin.java, src/main/java/com/dace/dmgr/gui/ItemBuilder.java, src/main/java/com/dace/dmgr/gui/Menu.java, src/main/java/com/dace/dmgr/gui/SkullIcon.java, src/main/java/com/dace/dmgr/gui/menu/ChatSoundMenu.java, src/main/java/com/dace/dmgr/gui/menu/MainMenu.java, src/main/java/com/dace/dmgr/gui/menu/OptionMenu.java, src/main/java/com/dace/dmgr/gui/menu/event/ChatSoundMenuEvent.java, src/main/java/com/dace/dmgr/gui/menu/event/MainMenuEvent.java, src/main/java/com/dace/dmgr/gui/menu/event/MenuEvent.java, src/main/java/com/dace/dmgr/gui/menu/event/OptionMenuEvent.java, src/main/java/com/dace/dmgr/gui/slot/ButtonSlot.java, src/main/java/com/dace/dmgr/system/EventListener.java, src/main/java/com/dace/dmgr/system/command/OptionCommand.java, src/main/java/com/dace/dmgr/user/ChatSound.java, src/main/java/com/dace/dmgr/user/Lobby.java, src/main/java/com/dace/dmgr/user/UserConfig.java, src/main/resources/plugin.yml
=> Feature/메뉴 기능 구현

pom.xml, src/main/java/com/dace/dmgr/user/Lobby.java, src/main/java/com/dace/dmgr/user/User.java, src/main/java/com/dace/dmgr/util/StringUtil.java, src/main/resources/plugin.yml
=> Feature/로비 상태창 추가

src/main/java/com/dace/dmgr/event/listener/OnEntityDamageByEntity.java
=> Bug/EntityDamageByEntity 이벤트 오류

src/main/java/com/dace/dmgr/DMGR.java
=> Feature/테스트용 코드 추가

src/main/java/com/dace/dmgr/combat/CombatTick.java, src/main/java/com/dace/dmgr/combat/action/ActionKey.java, src/main/java/com/dace/dmgr/combat/action/Reloadable.java, src/main/java/com/dace/dmgr/combat/action/WeaponController.java, src/main/java/com/dace/dmgr/combat/character/arkace/Arkace.java, src/main/java/com/dace/dmgr/combat/character/arkace/action/ArkaceWeapon.java, src/main/java/com/dace/dmgr/combat/entity/CombatUser.java, src/main/java/com/dace/dmgr/combat/event/listener/OnCombatUserAction.java, src/main/java/com/dace/dmgr/event/listener/OnPlayerArmorStandManipulate.java, src/main/java/com/dace/dmgr/event/listener/OnPlayerDropItem.java, src/main/java/com/dace/dmgr/event/listener/OnWeaponPreShoot.java, src/main/java/com/dace/dmgr/event/listener/OnWeaponPrepareShoot.java, src/main/java/com/dace/dmgr/system/Cooldown.java
=> Feature/재장전 시스템 수정

src/main/java/com/dace/dmgr/combat/Bullet.java, src/main/java/com/dace/dmgr/combat/Combat.java, src/main/java/com/dace/dmgr/combat/Hitscan.java, src/main/java/com/dace/dmgr/combat/Projectile.java, src/main/java/com/dace/dmgr/combat/character/arkace/action/ArkaceA1.java, src/main/java/com/dace/dmgr/combat/character/arkace/action/ArkaceWeapon.java, src/main/java/com/dace/dmgr/combat/entity/CombatEntity.java, src/main/java/com/dace/dmgr/combat/entity/CombatUser.java, src/main/java/com/dace/dmgr/combat/entity/Dummy.java, src/main/java/com/dace/dmgr/combat/entity/ICombatEntity.java, src/main/java/com/dace/dmgr/combat/entity/TemporalEntity.java, src/main/java/com/dace/dmgr/util/LocationUtil.java
Resolves #33 
치명타 적용 및 ArkaceWeapon에 적용해봄
테스트 안해봄
=> #33 치명타 기능 구현 완료

src/main/java/com/dace/dmgr/combat/Combat.java
=> fix: #41 getNearEnemy NPE

pom.xml
lombok 추가함
pom.xml 우클릭 > Maven > 프로젝트 다시 로드(Project reload) 하면 적용됨
=> chore: add lombok dependency

src/main/java/com/dace/dmgr/combat/action/Action.java, src/main/java/com/dace/dmgr/combat/action/Skill.java, src/main/java/com/dace/dmgr/combat/character/Character.java, src/main/java/com/dace/dmgr/combat/character/arkace/Arkace.java, src/main/java/com/dace/dmgr/combat/entity/CombatEntity.java, src/main/java/com/dace/dmgr/combat/entity/CombatUser.java, src/main/java/com/dace/dmgr/combat/entity/Hitbox.java, src/main/java/com/dace/dmgr/combat/event/CombatUserEvent.java, src/main/java/com/dace/dmgr/combat/event/combatuser/CombatUserActionEvent.java, src/main/java/com/dace/dmgr/gui/PlayerSkull.java, src/main/java/com/dace/dmgr/gui/item/ButtonItem.java, src/main/java/com/dace/dmgr/gui/item/CombatItem.java, src/main/java/com/dace/dmgr/gui/item/DisplayItem.java, src/main/java/com/dace/dmgr/lobby/ChatSound.java, src/main/java/com/dace/dmgr/lobby/User.java, src/main/java/com/dace/dmgr/system/task/TaskTimer.java
할 수 있는 곳 전부 lombok annotation으로 대체했음
제대로 돌아갈진 몰?루
=> #54 전체 코드에 lombok 적용

src/main/java/com/dace/dmgr/combat/action/SkillController.java, src/main/java/com/dace/dmgr/combat/entity/SummonEntity.java, src/main/resources/plugin.yml
- 플레이어가 소환할 수 있는 엔티티(SummonEntity) 추가
- GlowAPI dependency 추가
- 설치형 스킬의 설치 모드 UI 구현 (프로토타입)
=> #58 설치형 스킬 시스템

pom.xml, src/main/java/com/dace/dmgr/combat/action/ActionModule.java, src/main/java/com/dace/dmgr/combat/action/skill/Confirmable.java, src/main/java/com/dace/dmgr/combat/action/skill/LocationConfirmable.java, src/main/java/com/dace/dmgr/combat/action/skill/module/ConfirmModule.java, src/main/java/com/dace/dmgr/combat/action/skill/module/LocationConfirmModule.java, src/main/java/com/dace/dmgr/combat/action/weapon/module/ReloadModule.java, src/main/java/com/dace/dmgr/combat/action/weapon/module/SwapModule.java, src/main/java/com/dace/dmgr/combat/character/Character.java, src/main/java/com/dace/dmgr/combat/character/jager/Jager.java, src/main/java/com/dace/dmgr/combat/character/jager/action/JagerA1.java, src/main/java/com/dace/dmgr/combat/character/jager/action/JagerA1Entity.java, src/main/java/com/dace/dmgr/combat/character/jager/action/JagerA2Entity.java, src/main/java/com/dace/dmgr/combat/character/jager/action/JagerUltEntity.java, src/main/java/com/dace/dmgr/combat/character/jager/action/JagerWeaponInfo.java, src/main/java/com/dace/dmgr/combat/entity/Attacker.java, src/main/java/com/dace/dmgr/combat/entity/CombatUser.java, src/main/java/com/dace/dmgr/combat/entity/Damageable.java, src/main/java/com/dace/dmgr/combat/entity/Healable.java, src/main/java/com/dace/dmgr/combat/entity/Healer.java, src/main/java/com/dace/dmgr/combat/entity/Jumpable.java, src/main/java/com/dace/dmgr/combat/entity/Movable.java, src/main/java/com/dace/dmgr/combat/entity/module/CombatEntityModule.java, src/main/java/com/dace/dmgr/combat/entity/module/JumpModule.java
=> 궁극기 상태에서 궁극기 충전 오류 수정

src/main/java/com/dace/dmgr/combat/CombatUtil.java, src/main/java/com/dace/dmgr/combat/action/weapon/module/FullAutoModule.java, src/main/java/com/dace/dmgr/combat/action/weapon/module/GradualSpreadModule.java, src/main/java/com/dace/dmgr/combat/character/arkace/action/ArkaceWeapon.java, src/main/java/com/dace/dmgr/combat/character/arkace/action/ArkaceWeaponInfo.java, src/main/java/com/dace/dmgr/combat/entity/CombatUser.java, src/main/java/com/dace/dmgr/system/Cooldown.java
- GradualSpreadModule(점진적 탄퍼짐 모듈) 추가
- 기존 탄퍼짐 시스템 제거
=> 탄퍼짐 시스템 수정

pom.xml, src/main/java/com/dace/dmgr/DMGR.java, src/main/java/com/dace/dmgr/GeneralConfig.java, src/main/java/com/dace/dmgr/event/EventManager.java, src/main/java/com/dace/dmgr/event/listener/OnAsyncPlayerChat.java, src/main/java/com/dace/dmgr/event/listener/OnPlayServerPlayerInfo.java, src/main/java/com/dace/dmgr/game/Game.java, src/main/java/com/dace/dmgr/game/GameUser.java, src/main/java/com/dace/dmgr/game/Tier.java, src/main/java/com/dace/dmgr/item/gui/Menu.java, src/main/java/com/dace/dmgr/user/User.java, src/main/java/com/dace/dmgr/user/UserData.java, src/main/java/com/dace/dmgr/util/StringFormUtil.java, src/main/resources/plugin.yml
- Tabbed dependency 추가
- 로비 TAB 리스트 개편
- 채팅의 플레이어 이름 포맷에 티어와 레벨 표시
- 인게임 전적 창 구현
=> 인게임 전적창 구현

src/main/java/com/dace/dmgr/combat/character/jager/action/JagerA1Entity.java, src/main/java/com/dace/dmgr/combat/character/jager/action/JagerA2Entity.java, src/main/java/com/dace/dmgr/combat/character/jager/action/JagerUltEntity.java, src/main/java/com/dace/dmgr/combat/entity/AbstractCombatEntity.java, src/main/java/com/dace/dmgr/combat/entity/CombatEntity.java, src/main/java/com/dace/dmgr/combat/entity/CombatUser.java, src/main/java/com/dace/dmgr/combat/entity/Dummy.java, src/main/java/com/dace/dmgr/combat/entity/HasReadyTime.java, src/main/java/com/dace/dmgr/combat/entity/SummonEntity.java, src/main/java/com/dace/dmgr/combat/entity/TemporalEntity.java, src/main/java/com/dace/dmgr/combat/entity/module/DamageModule.java, src/main/java/com/dace/dmgr/combat/entity/module/HealModule.java, src/main/java/com/dace/dmgr/combat/entity/module/ReadyTimeModule.java
- 적 처치 점수 매커니즘 수정
- 자해 피해량 누적 시스템 추가
- CombatEntity 생명 주기 삭제
- ReadyTimeModule(준비 대기시간 모듈) 추가
=> 자해 누적 시스템 구현 및 처치 점수 매커니즘 수정

src/main/java/com/dace/dmgr/combat/entity/CombatEntity.java, src/main/java/com/dace/dmgr/combat/entity/CombatUser.java, src/main/java/com/dace/dmgr/combat/entity/module/DamageModule.java, src/main/java/com/dace/dmgr/game/GameUser.java, src/main/java/com/dace/dmgr/util/Cooldown.java, src/main/java/com/dace/dmgr/util/HologramUtil.java
- 홀로그램 수정 기능 추가
- Damageable 엔티티의 체력바 홀로그램 추가
- 적 타격 시 일시적으로 체력바 표시
=> 적 타격 시 체력 표시

src/main/java/com/dace/dmgr/combat/entity/CombatUser.java, src/main/java/com/dace/dmgr/game/Game.java, src/main/java/com/dace/dmgr/game/GameUser.java, src/main/java/com/dace/dmgr/user/User.java, src/main/java/com/dace/dmgr/user/UserData.java
- UserData에 게임 전적 항목 추가
- 게임 진행 및 종료 시 전적 반영
- 로비 TAB 리스트에 전적 반영
=> 게임 전적 기록 및 반영

src/main/java/com/dace/dmgr/combat/character/CharacterType.java, src/main/java/com/dace/dmgr/combat/character/arkace/action/ArkaceP1.java, src/main/java/com/dace/dmgr/combat/character/vellion/Vellion.java, src/main/java/com/dace/dmgr/combat/character/vellion/action/VellionA1.java, src/main/java/com/dace/dmgr/combat/character/vellion/action/VellionA1Info.java, src/main/java/com/dace/dmgr/combat/character/vellion/action/VellionA2.java, src/main/java/com/dace/dmgr/combat/character/vellion/action/VellionA2Info.java, src/main/java/com/dace/dmgr/combat/character/vellion/action/VellionA3.java, src/main/java/com/dace/dmgr/combat/character/vellion/action/VellionA3Info.java, src/main/java/com/dace/dmgr/combat/character/vellion/action/VellionP1.java, src/main/java/com/dace/dmgr/combat/character/vellion/action/VellionP1Info.java, src/main/java/com/dace/dmgr/combat/character/vellion/action/VellionP2.java, src/main/java/com/dace/dmgr/combat/character/vellion/action/VellionP2Info.java, src/main/java/com/dace/dmgr/combat/character/vellion/action/VellionUlt.java, src/main/java/com/dace/dmgr/combat/character/vellion/action/VellionUltInfo.java, src/main/java/com/dace/dmgr/combat/character/vellion/action/VellionWeapon.java, src/main/java/com/dace/dmgr/combat/character/vellion/action/VellionWeaponInfo.java, src/main/java/com/dace/dmgr/combat/entity/CombatUser.java, src/main/java/com/dace/dmgr/combat/entity/module/DamageModule.java, src/main/java/com/dace/dmgr/combat/entity/module/HealModule.java, src/main/java/com/dace/dmgr/combat/entity/module/statuseffect/HealBlock.java, src/main/java/com/dace/dmgr/combat/entity/module/statuseffect/Invulnerable.java, src/main/java/com/dace/dmgr/combat/entity/module/statuseffect/Poison.java, src/main/java/com/dace/dmgr/combat/entity/module/statuseffect/StatusEffectType.java, src/main/java/com/dace/dmgr/combat/entity/temporal/Dummy.java, src/main/java/com/dace/dmgr/event/listener/OnPlayerToggleFlight.java, src/main/java/com/dace/dmgr/util/NamedSound.java, src/main/java/com/dace/dmgr/util/StringFormUtil.java
- 전투원 '벨리온' 추가
- Dummy(더미 엔티티) - 유리 색깔로 아군 및 적군 구별
- HealBlock(회복 차단) 상태 효과 추가
=> 전투원 '벨리온' 추가

src/main/java/com/dace/dmgr/combat/character/CharacterType.java, src/main/java/com/dace/dmgr/combat/character/inferno/Inferno.java, src/main/java/com/dace/dmgr/combat/character/jager/Jager.java, src/main/java/com/dace/dmgr/combat/character/magritta/Magritta.java, src/main/java/com/dace/dmgr/combat/character/magritta/action/MagrittaA1.java, src/main/java/com/dace/dmgr/combat/character/magritta/action/MagrittaA1Info.java, src/main/java/com/dace/dmgr/combat/character/magritta/action/MagrittaA2.java, src/main/java/com/dace/dmgr/combat/character/magritta/action/MagrittaA2Info.java, src/main/java/com/dace/dmgr/combat/character/magritta/action/MagrittaP1.java, src/main/java/com/dace/dmgr/combat/character/magritta/action/MagrittaP1Info.java, src/main/java/com/dace/dmgr/combat/character/magritta/action/MagrittaT1.java, src/main/java/com/dace/dmgr/combat/character/magritta/action/MagrittaT1Info.java, src/main/java/com/dace/dmgr/combat/character/magritta/action/MagrittaUlt.java, src/main/java/com/dace/dmgr/combat/character/magritta/action/MagrittaUltInfo.java, src/main/java/com/dace/dmgr/combat/character/magritta/action/MagrittaWeapon.java, src/main/java/com/dace/dmgr/combat/character/magritta/action/MagrittaWeaponInfo.java, src/main/java/com/dace/dmgr/combat/entity/CombatUser.java, src/main/java/com/dace/dmgr/combat/entity/Property.java, src/main/java/com/dace/dmgr/combat/entity/module/JumpModule.java, src/main/java/com/dace/dmgr/util/NamedSound.java
- 전투원 '마그리타' 추가
- '마그리타' 전투원 상호작용 대사 추가
- 적 타격 효과음 중첩 방지
=> 전투원 '마그리타' 추가

src/main/java/com/dace/dmgr/game/map/TeamDeathmatchMap.java
=> 신규 데스매치 맵 추가

src/main/java/com/dace/dmgr/combat/character/CharacterType.java, src/main/java/com/dace/dmgr/item/gui/SelectChar.java
- 전투원 중복 시 선택 안 되도록 수정
- SelectChar(전투원 선택 GUI) - 팀원이 선택한 전투원 표시
=> 전투원 중복 선택 방지

pom.xml, src/main/java/com/dace/dmgr/combat/character/ched/action/ChedP1.java, src/main/java/com/dace/dmgr/combat/character/inferno/Inferno.java, src/main/java/com/dace/dmgr/combat/character/inferno/action/InfernoA2.java, src/main/java/com/dace/dmgr/combat/character/jager/action/JagerA1.java, src/main/java/com/dace/dmgr/combat/character/magritta/action/MagrittaT1.java, src/main/java/com/dace/dmgr/combat/character/palas/Palas.java, src/main/java/com/dace/dmgr/combat/character/palas/action/PalasA1.java, src/main/java/com/dace/dmgr/combat/character/palas/action/PalasA3.java, src/main/java/com/dace/dmgr/combat/character/quaker/Quaker.java, src/main/java/com/dace/dmgr/combat/character/quaker/action/QuakerA2.java, src/main/java/com/dace/dmgr/combat/character/quaker/action/QuakerUlt.java, src/main/java/com/dace/dmgr/combat/character/silia/action/SiliaP2.java, src/main/java/com/dace/dmgr/combat/character/vellion/Vellion.java, src/main/java/com/dace/dmgr/combat/character/vellion/action/VellionA2.java, src/main/java/com/dace/dmgr/combat/character/vellion/action/VellionA3.java, src/main/java/com/dace/dmgr/combat/character/vellion/action/VellionUlt.java, src/main/java/com/dace/dmgr/combat/entity/CombatUser.java, src/main/java/com/dace/dmgr/combat/entity/module/StatusEffectModule.java, src/main/java/com/dace/dmgr/event/listener/OnPlayServerNamedSoundEffect.java
- 일부 전투원의 처치 지원 점수가 처치 기여도 비례로 적용되는 문제 수정
- '마그리타' 특성 1번 수치 표시가 사라지지 않는 버그 수정
- '팔라스' 액티브 3번으로 감소된 체력이 복구되지 않는 버그 수정
- '팔라스' 액티브 3번 - 범위 효과가 적 방벽을 통과하는 버그 수정
- '예거' 액티브 1번 - 설랑이 적을 감지했을 때 체력이 감소하는 버그 수정
- '실리아' 액티브 3번 - 사용 중 발소리가 사라지지 않는 버그 수정
- '실리아' 패시브 2번 및 '체드' 패시브 1번 - 벽타기 사용이 간헐적으로 취소되는 버그 수정
=> v0.12.1 완료

pom.xml, src/main/java/com/dace/dmgr/combat/combatant/silia/SiliaA1.java, src/main/java/com/dace/dmgr/combat/combatant/silia/SiliaWeapon.java
- '실리아' 액티브 1번 - 적 처치 시 무기가 투명화되는 버그 수정
- '실리아' 특성 - 일격의 백어택 판정 개선
=> v0.13.2 완료

pom.xml, src/main/java/com/dace/dmgr/YamlFile.java, src/main/java/com/dace/dmgr/combat/entity/module/StatusEffectModule.java, src/main/java/com/dace/dmgr/event/listener/OnEntityDamage.java
- YamlFile - ConfigurationSection 인스턴스를 config에서 직접 불러오도록 수정 (#217)
- 게임 스폰 지역 및 자유전투 대기실에서 전투원을 선택하지 않았을 때 피해를 받을 수 있는 문제 수정
- 플레이어가 사망한 상태에서 상태 효과가 유지되는 문제 수정
=> v0.13.3 완료

pom.xml, src/main/java/com/dace/dmgr/combat/combatant/silia/Silia.java, src/main/java/com/dace/dmgr/combat/combatant/vellion/Vellion.java, src/main/java/com/dace/dmgr/combat/entity/CombatUser.java
- 자기 자신의 처치를 기여할 수 있는 버그 수정
- Combatant.onAttack, Combatant.onGiveHeal이 우선 호출되도록 수정
=> v0.14.3 완료

src/main/java/com/dace/dmgr/Timespan.java
- 변수명 rename
- Serializer.serialize()가 "ticks" 단위가 아닌 다른 단위로도 나오도록 수정
- Timespan.MAX를 {"infinity": 1}로 serialize하도록 수정
- 기타 자잘한 로직 수정
=> Refactor: Timespan

src/main/java/com/dace/dmgr/DMGR.java, src/main/java/com/dace/dmgr/GeneralConfig.java, src/main/java/com/dace/dmgr/GlobalLocation.java, src/main/java/com/dace/dmgr/Timespan.java, src/main/java/com/dace/dmgr/YamlFile.java, src/main/java/com/dace/dmgr/combat/FreeCombat.java, src/main/java/com/dace/dmgr/combat/TrainingCenter.java, src/main/java/com/dace/dmgr/user/UserData.java
- 모든 위치 좌표를 설정 파일에서 관리
- FreeCombatConfig(자유 전투 설정) 추가
- 자체 직렬화 시스템 구현 - YamlFile.Serializer 추가
- GlobalLocation(전역 위치), Timespan, UserData의 직렬화 구현
- ListEntry 제거
- TypeToken(타입 토큰)을 이용한 Enum 및 List 직렬화
=> YamlFile, GeneralConfig 리팩토링

pom.xml, src/main/java/com/dace/dmgr/DMGR.java, src/main/java/com/dace/dmgr/PlayerSkin.java, src/main/java/com/dace/dmgr/combat/combatant/Combatant.java, src/main/java/com/dace/dmgr/combat/combatant/CombatantType.java, src/main/java/com/dace/dmgr/combat/combatant/SelectChar.java, src/main/java/com/dace/dmgr/combat/combatant/SelectCharInfo.java, src/main/java/com/dace/dmgr/combat/entity/combatuser/CombatUser.java, src/main/java/com/dace/dmgr/combat/entity/temporary/dummy/Dummy.java, src/main/java/com/dace/dmgr/combat/entity/temporary/spawnhandler/PlayerNPCSpawnHandler.java, src/main/java/com/dace/dmgr/game/GameTabListProfile.java, src/main/java/com/dace/dmgr/item/ItemBuilder.java, src/main/java/com/dace/dmgr/menu/BlockList.java, src/main/java/com/dace/dmgr/menu/Menu.java, src/main/java/com/dace/dmgr/menu/Stat.java, src/main/java/com/dace/dmgr/user/LobbyTabListProfile.java, src/main/java/com/dace/dmgr/user/TabListProfile.java, src/main/java/com/dace/dmgr/user/User.java, src/main/java/com/dace/dmgr/user/UserData.java
- 자체 스킨 변경 시스템 구현
- PlayerSkin 리팩토링
- SkinsRestorer dependency 제거
- Jetbrains Annotations dependency 추가
- PlayerSkin.Async(비동기 스킨) 추가 - 비동기 스킨 리팩토링
=> SkinsRestorer dependency 제거
